name: 'action-json-file-to-env'
author: 'hocgin'
description: '.json file to env variable'
inputs:
  debug:
    required: false
    description: 'debug mode'
  type:
    required: false
    description: 'eg: github, local'
    default: 'github'
  file:
    required: false
    description: '.json file path, eg: .github/workflows/env.json'
#
  owner:
    required: false
    description: 'resp owner'
  repo:
    required: false
    description: 'resp'
  branch:
    required: false
    description: 'branch'
#outputs:
runs:
  using: node16
  main: dist/index.js
